

#ifndef _D_ERROR_NETWORK_DEFINE_H_
#define _D_ERROR_NETWORK_DEFINE_H_

#include "DErrorDefine.h"

enum
{
	/* socket发生错误 */
	ERROR_NETWORK_BASE_SOCKET_ERROR						= (long)(ERROR_NETWORK_BASE + 1),

	/* 对方断开一个已有连接 */
	ERROR_NETWORK_BASE_SOCKET_RESET						= (long)(ERROR_NETWORK_BASE + 2),

	/* 一个已有连接被关闭 */
	ERROR_NETWORK_BASE_SOCKET_CLOSE						= (long)(ERROR_NETWORK_BASE + 3),

	/* 绑定地址或端口时出错 */
	ERROR_NETWORK_BASE_SOCKET_BIND_ERROR				= (long)(ERROR_NETWORK_BASE + 4),

	/* 连接对端时出错 */
	ERROR_NETWORK_BASE_CONNECT_ERROR					= (long)(ERROR_NETWORK_BASE + 5),

	/* 连接超时 */
	ERROR_NETWORK_BASE_CONNECT_TIMEOUT					= (long)(ERROR_NETWORK_BASE + 6),

	/* DNS解析失败 */
	ERROR_NETWORK_BASE_DNS_FAILURE						= (long)(ERROR_NETWORK_BASE + 7),

	/* 代理服务器无法访问 */
	ERROR_NETWORK_BASE_PROXY_SERVER_UNAVAILABLE			= (long)(ERROR_NETWORK_BASE + 8),

	/* 不知名的错误 */
	ERROR_NETWORK_BASE_UNKNOWN_ERROR					= (long)(ERROR_NETWORK_BASE + 9),

	/* 没有这个服务 */
	ERROR_NETWORK_BASE_NO_SERVICE						= (long)(ERROR_NETWORK_BASE + 10),
};

#endif	// _D_ERROR_NETWORK_DEFINE_H_